server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: public

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/SpringDemoRealm
          jwk-set-uri: http://localhost:8088/realms/SpringDemoRealm/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8088/
  realm: SpringDemoRealm
  username: tamerlan.shamelov
  password: Arnur310310
  secret: 67LBr1fa290wHUmuhggiPpPARIZ2NfnW
  clientId: spring-demo-app